# Generated by Django 5.2.6 on 2025-09-11 13:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, help_text='Add one or more URLs separated by commas.', size=None)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('position', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
