# Generated by Django 5.2.6 on 2025-09-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_remove_project_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first'),
        ),
    ]
